CREATE TABLE DEPENDENTE(
	ID				UNIQUEIDENTIFIER NOT NULL,
	NOME			NVARCHAR(150) NOT NULL,
	DATANASCIMENTO	DATE NOT NULL,
	FUNCIONARIOID	UNIQUEIDENTIFIER NOT NULL,
	PRIMARY	KEY(ID),
	FOREIGN KEY(FUNCIONARIOID) 
		REFERENCES FUNCIONARIO(ID))
GO