CREATE TABLE FUNCIONARIO(
		ID				UNIQUEIDENTIFIER NOT NULL,
		NOME			NVARCHAR(150) NOT NULL,
		CPF				NVARCHAR(11) NOT NULL UNIQUE,
		MATRICULA		NVARCHAR(10) NOT NULL,
		DATAADMISSAO	DATE NOT NULL,
		SALARIO			DECIMAL(18,2) NOT NULL,
		PRIMARY KEY(ID))
GO